// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using edvaudin.ExerciseTracker.Context;

#nullable disable

namespace edvaudin.ExerciseTracker.Migrations;

[DbContext(typeof(ExerciseContext))]
partial class ExerciseContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "7.0.2")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("edvaudin.ExerciseTracker.Models.Exercise", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Comments")
                    .HasMaxLength(255)
                    .HasColumnType("nvarchar(255)");

                b.Property<DateTime>("DateEnd")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("DateStart")
                    .HasColumnType("datetime2");

                b.Property<TimeSpan>("Duration")
                    .HasColumnType("time");

                b.HasKey("Id");

                b.ToTable("Exercises");
            });
#pragma warning restore 612, 618
    }
}
