global using ExerciseTracker.Forser.Context;
global using ExerciseTracker.Forser.Controllers;
global using ExerciseTracker.Forser.Repository;
global using ExerciseTracker.Forser.Services;
global using ExerciseTracker.Forser.UI;
global using ExerciseTracker.Forser.Models;
global using Spectre.Console;
global using Microsoft.EntityFrameworkCore;
global using System.Globalization;